import os

import psycopg
from psycopg.rows import dict_row


DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/reviewblog")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)


def get_connection():
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def init_db():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS reviews (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title TEXT NOT NULL,
                    author TEXT NOT NULL,
                    category TEXT NOT NULL CHECK (category IN ('book', 'movie', 'music', 'other')),
                    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
                    hearts_count INTEGER NOT NULL DEFAULT 0 CHECK (hearts_count >= 0),
                    excerpt TEXT NOT NULL,
                    body TEXT NOT NULL,
                    cover_url TEXT,
                    created_at TIMESTAMPTZ NOT NULL
                )
                """
            )
            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_reviews_created_at
                ON reviews (created_at DESC, id DESC)
                """
            )
            cursor.execute(
                """
                ALTER TABLE reviews
                ADD COLUMN IF NOT EXISTS hearts_count INTEGER NOT NULL DEFAULT 0
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS site_stats (
                    name TEXT PRIMARY KEY,
                    value INTEGER NOT NULL DEFAULT 0,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cursor.execute(
                """
                INSERT INTO site_stats (name, value)
                VALUES ('home_views', 0)
                ON CONFLICT (name) DO NOTHING
                """
            )


def get_site_view_count():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT value
                FROM site_stats
                WHERE name = 'home_views'
                """
            )
            row = cursor.fetchone()
            return row["value"] if row else 0


def increment_site_view_count():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO site_stats (name, value, updated_at)
                VALUES ('home_views', 1, NOW())
                ON CONFLICT (name)
                DO UPDATE SET
                    value = site_stats.value + 1,
                    updated_at = NOW()
                RETURNING value
                """
            )
            return cursor.fetchone()["value"]


def list_reviews():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT id, title, author, category, rating, hearts_count, excerpt, cover_url, created_at
                FROM reviews
                ORDER BY created_at DESC, id DESC
                """
            )
            return cursor.fetchall()


def get_review(review_id):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT id, title, author, category, rating, hearts_count, excerpt, body, cover_url, created_at
                FROM reviews
                WHERE id = %s
                """,
                (review_id,),
            )
            return cursor.fetchone()


def create_review(title, author, category, rating, excerpt, body, cover_url, created_at):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO reviews (title, author, category, rating, excerpt, body, cover_url, created_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id, title, author, category, rating, hearts_count, excerpt, body, cover_url, created_at
                """,
                (title, author, category, rating, excerpt, body, cover_url, created_at),
            )
            return cursor.fetchone()


def update_review(review_id, title, author, category, rating, excerpt, body, cover_url):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE reviews
                SET title = %s,
                    author = %s,
                    category = %s,
                    rating = %s,
                    excerpt = %s,
                    body = %s,
                    cover_url = %s
                WHERE id = %s
                RETURNING id, title, author, category, rating, hearts_count, excerpt, body, cover_url, created_at
                """,
                (title, author, category, rating, excerpt, body, cover_url, review_id),
            )
            return cursor.fetchone()


def set_review_heart(review_id, hearted):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            if hearted:
                cursor.execute(
                    """
                    UPDATE reviews
                    SET hearts_count = hearts_count + 1
                    WHERE id = %s
                    RETURNING hearts_count
                    """,
                    (review_id,),
                )
            else:
                cursor.execute(
                    """
                    UPDATE reviews
                    SET hearts_count = GREATEST(hearts_count - 1, 0)
                    WHERE id = %s
                    RETURNING hearts_count
                    """,
                    (review_id,),
                )
            return cursor.fetchone()


def delete_review(review_id):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                DELETE FROM reviews
                WHERE id = %s
                RETURNING id, title, author, category, rating, hearts_count, excerpt, body, cover_url, created_at
                """,
                (review_id,),
            )
            return cursor.fetchone()
